### ISSUE TITLE
What are your thoughts on excitonium?

### ISSUE THREAD

**Issue by sindresorhus** [zommuter/ama#1]

**Comment by zommuter** [comment]
It's very exciting (pun intended) for me, since I was quite involved with other quasi-particles such as surface plasmon polaritons or phonons. I'm not sure about the implications yet since I haven't spent much time reading about excitonium so far, but hey, maybe it'll offer the means for room-temperature superconductors, who knows...

PS: Sorry for the late reply, I had my notification settings messed up...
